<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>edu.asu.cse360.local</groupId>
        <artifactId>cse360-course-workspace</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>username-recognizer-testbed-f26</artifactId>

    <build>
        <sourceDirectory>${project.basedir}/../../CSE-360-Software-Engineering/HW1-linhmho/UserNameRecognizerTestbed-F26/src</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration><mainClass>userNameRecognizerTestbed.UserNameRecognizerTestbed</mainClass></configuration>
            </plugin>
        </plugins>
    </build>
</project>
